name: gestimator
version: 2.0.0
summary: GEstimator is a simple civil estimation software written in Python and GTK+
description: |
  GEstimator is a simple civil estimation software written in Python and GTK+. GEstimator can prepare estimates along with rate analysis and supports multiple databases.
icon: gui/GEstimator.svg
grade: devel
confinement: devmode
base: core18


apps:
  gestimator:
    command: bin/GEstimator.py
    desktop: share/applications/GEstimator.desktop


parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk

    plugin: make
    build-packages:
    - build-essential
    - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
      
  gestimator:
    source: https://github.com/manuvarkey/GEstimator.git
    plugin: python
    python-version: python3
    
    
plugs:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  
  # GNOME and Gtk runtime via content sharing
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes


